# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flight.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'flight.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66light.proto\x12\x08\x66lightdb\"T\n\x0c\x46lightRecord\x12\x11\n\tflightNum\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08numSeats\x18\x03 \x01(\x05\x12\x10\n\x08numAvail\x18\x04 \x01(\x05\"\x8a\x01\n\x0b\x46lightTable\x12\x33\n\x07records\x18\x01 \x03(\x0b\x32\".flightdb.FlightTable.RecordsEntry\x1a\x46\n\x0cRecordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.flightdb.FlightRecord:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flight_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLIGHTTABLE_RECORDSENTRY']._loaded_options = None
  _globals['_FLIGHTTABLE_RECORDSENTRY']._serialized_options = b'8\001'
  _globals['_FLIGHTRECORD']._serialized_start=26
  _globals['_FLIGHTRECORD']._serialized_end=110
  _globals['_FLIGHTTABLE']._serialized_start=113
  _globals['_FLIGHTTABLE']._serialized_end=251
  _globals['_FLIGHTTABLE_RECORDSENTRY']._serialized_start=181
  _globals['_FLIGHTTABLE_RECORDSENTRY']._serialized_end=251
# @@protoc_insertion_point(module_scope)
