# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hotel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hotel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhotel.proto\x12\x07hoteldb\"R\n\x0bHotelRecord\x12\x10\n\x08location\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08numRooms\x18\x03 \x01(\x05\x12\x10\n\x08numAvail\x18\x04 \x01(\x05\"\x85\x01\n\nHotelTable\x12\x31\n\x07records\x18\x01 \x03(\x0b\x32 .hoteldb.HotelTable.RecordsEntry\x1a\x44\n\x0cRecordsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.hoteldb.HotelRecord:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hotel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HOTELTABLE_RECORDSENTRY']._loaded_options = None
  _globals['_HOTELTABLE_RECORDSENTRY']._serialized_options = b'8\001'
  _globals['_HOTELRECORD']._serialized_start=24
  _globals['_HOTELRECORD']._serialized_end=106
  _globals['_HOTELTABLE']._serialized_start=109
  _globals['_HOTELTABLE']._serialized_end=242
  _globals['_HOTELTABLE_RECORDSENTRY']._serialized_start=174
  _globals['_HOTELTABLE_RECORDSENTRY']._serialized_end=242
# @@protoc_insertion_point(module_scope)
